\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Two-Way ANOVA project},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Two-Way ANOVA project}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

\hypertarget{collaboration-rules}{%
\subsection{Collaboration rules:}\label{collaboration-rules}}

You may consult with up to two classmates for help with this project,
but use your own data. Please identify who you collaborate with here.

\textbf{Response:}

\hypertarget{instructions}{%
\section{Instructions}\label{instructions}}

Write a report that includes an introduction to the data, appropriate
EDA, model specification, the checking of conditions, and in context
conclusions. To include sections in your report use the \# as
illustrated by the \# Instructions for this section. Larger section
headings have one \#, smaller subsection headings have \#\# or \#\#\# or
even \#\#\#\#. There should be a coherent and well-organized narrative
in addition to appropriate code and figures.

\hypertarget{car-data}{%
\section{Car data}\label{car-data}}

The dataset contains the Price, mileage and year of 3 different types of
cars (BMW X3, Honda civic, Ford Taurus) at two different locations
(20010 \& 90095)

\hypertarget{eda}{%
\subsection{EDA}\label{eda}}

\hypertarget{read-in-the-data-and-report-the-mean-and-standard-deviation}{%
\subsubsection{Read in the data and report the mean and standard
deviation}\label{read-in-the-data-and-report-the-mean-and-standard-deviation}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(readr)}
\NormalTok{cars <-}\StringTok{ }\KeywordTok{read_csv}\NormalTok{(}\StringTok{"datacarrevise.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parsed with column specification:
## cols(
##   year = col_double(),
##   price = col_double(),
##   mileage = col_double(),
##   zipcode = col_double(),
##   model = col_character()
## )
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cars}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 300 x 5
##     year price mileage zipcode model 
##    <dbl> <dbl>   <dbl>   <dbl> <chr> 
##  1  2018  30.9    31.5   20010 BMW X3
##  2  2017  24.9    24.7   20010 BMW X3
##  3  2019  28.6    20.7   20010 BMW X3
##  4  2016  19.7    50.9   20010 BMW X3
##  5  2017  25.8    30.4   20010 BMW X3
##  6  2017  24.7    34.8   20010 BMW X3
##  7  2016  19.7    37.7   20010 BMW X3
##  8  2019  48.0    14.2   20010 BMW X3
##  9  2019  52.4    11.2   20010 BMW X3
## 10  2017  27.6    25.0   20010 BMW X3
## # ... with 290 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cars2 <-}\StringTok{ }\NormalTok{cars}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{( }\DataTypeTok{zipcode =} \KeywordTok{as.character}\NormalTok{(zipcode))}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(zipcode, model)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{mean =} \KeywordTok{mean}\NormalTok{(price), }\DataTypeTok{sd =} \KeywordTok{sd}\NormalTok{(price))}
\NormalTok{cars2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 4
## # Groups:   zipcode [2]
##   zipcode model        mean    sd
##   <chr>   <chr>       <dbl> <dbl>
## 1 20010   BMW X3       26.9  9.04
## 2 20010   Ford Taurus  14.0  5.65
## 3 20010   Honda Civic  17.6  6.02
## 4 90095   BMW X3       24.4  4.54
## 5 90095   Ford Taurus  14.1  3.40
## 6 90095   Honda Civic  17.8  3.37
\end{verbatim}

It seems like thare is aproblem with standard deviation variabilty
because 9.044/3.373 \textgreater{} 2

\hypertarget{side-by-side-dotplot}{%
\subsubsection{side-by-side dotplot}\label{side-by-side-dotplot}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{gf_point}\NormalTok{(price}\OperatorTok{~}\NormalTok{model }\OperatorTok{|}\StringTok{ }\NormalTok{zipcode, }\DataTypeTok{data =}\NormalTok{ cars)}
\end{Highlighting}
\end{Shaded}

\includegraphics{LastName_TWO-way-ANOVA_project_files/figure-latex/unnamed-chunk-3-1.pdf}
From the dot plot, it seems like BMW X3C has the highest price compared
to the other 2 models but price is higher for 20010 zipcode. For the
other two models, it seems like there's not much of a different in price
between the 20020 and 90095 zipcode but 20010 has more variability.

\hypertarget{interaction-plot}{%
\subsubsection{Interaction plot}\label{interaction-plot}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{with}\NormalTok{(cars, }\KeywordTok{interaction.plot}\NormalTok{(model, zipcode, price, }\DataTypeTok{lwd =} \DecValTok{2}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"darkgreen"}\NormalTok{, }\StringTok{"purple"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{LastName_TWO-way-ANOVA_project_files/figure-latex/unnamed-chunk-4-1.pdf}
From the interaction plot, BMW X3 has the highest mean price for both
location while Ford Taurus has the lowest price. The pattern of the two
lines are similar with the first line has a bit different slope but the
difference is not that big so I would say that they do have a parallel
slope hence no important interaction presence.

\hypertarget{fit-check-condition}{%
\subsection{Fit \& Check condition}\label{fit-check-condition}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cars3 <-}\StringTok{ }\NormalTok{cars}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{age =} \DecValTok{2020} \OperatorTok{-}\StringTok{ }\NormalTok{year)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{( }\DataTypeTok{zipcode =} \KeywordTok{as.character}\NormalTok{(zipcode))}
\NormalTok{cars3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 300 x 6
##     year price mileage zipcode model    age
##    <dbl> <dbl>   <dbl> <chr>   <chr>  <dbl>
##  1  2018  30.9    31.5 20010   BMW X3     2
##  2  2017  24.9    24.7 20010   BMW X3     3
##  3  2019  28.6    20.7 20010   BMW X3     1
##  4  2016  19.7    50.9 20010   BMW X3     4
##  5  2017  25.8    30.4 20010   BMW X3     3
##  6  2017  24.7    34.8 20010   BMW X3     3
##  7  2016  19.7    37.7 20010   BMW X3     4
##  8  2019  48.0    14.2 20010   BMW X3     1
##  9  2019  52.4    11.2 20010   BMW X3     1
## 10  2017  27.6    25.0 20010   BMW X3     3
## # ... with 290 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cars4 <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(price}\OperatorTok{~}\StringTok{ }\NormalTok{mileage }\OperatorTok{+}\StringTok{ }\NormalTok{age }\OperatorTok{+}\NormalTok{model }\OperatorTok{+}\StringTok{ }\NormalTok{zipcode, }\DataTypeTok{data =}\NormalTok{ cars3)}
\KeywordTok{summary}\NormalTok{(cars4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = price ~ mileage + age + model + zipcode, data = cars3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.2401 -1.9434 -0.8036  1.2699 22.1184 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(>|t|)    
## (Intercept)      32.19740    0.55205  58.324  < 2e-16 ***
## mileage          -0.09637    0.01336  -7.211 4.71e-12 ***
## age              -0.79147    0.14967  -5.288 2.42e-07 ***
## modelFord Taurus -8.38029    0.58765 -14.261  < 2e-16 ***
## modelHonda Civic -9.23250    0.54665 -16.889  < 2e-16 ***
## zipcode90095     -1.47985    0.44384  -3.334 0.000965 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.824 on 294 degrees of freedom
## Multiple R-squared:  0.7421, Adjusted R-squared:  0.7377 
## F-statistic: 169.2 on 5 and 294 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mplot}\NormalTok{(cars4, }\DataTypeTok{which =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [[1]]
\end{verbatim}

\includegraphics{LastName_TWO-way-ANOVA_project_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mplot}\NormalTok{(cars4, }\DataTypeTok{which =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [[1]]
\end{verbatim}

\includegraphics{LastName_TWO-way-ANOVA_project_files/figure-latex/unnamed-chunk-5-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{gf_point}\NormalTok{(}\KeywordTok{log}\NormalTok{(sd) }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(mean), }\DataTypeTok{data =}\NormalTok{ cars2) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{gf_lm}\NormalTok{(}\KeywordTok{log}\NormalTok{(sd) }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(mean), }\DataTypeTok{data =}\NormalTok{ cars2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{LastName_TWO-way-ANOVA_project_files/figure-latex/unnamed-chunk-5-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{lm}\NormalTok{(}\KeywordTok{log}\NormalTok{(sd) }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(mean), }\DataTypeTok{data =}\NormalTok{ cars2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = log(sd) ~ log(mean), data = cars2)
## 
## Coefficients:
## (Intercept)    log(mean)  
##     -0.4943       0.7217
\end{verbatim}

Since the data has 2 covariates which are mileage and age, I decided to
fit a model that includes the covariate. From the two sample t-test, the
intercept is the BMW X3 at 20010 zipcode. The rest of the variables have
a very low p-value which means I could include these variables into my
model.From the residual vs fitted plot, It seems like the linearity and
equal variance for a linear regression are not met. Curve is formed and
the points spread out at the end of the curve.And from the normality
plot, there is a tail on the right end of the curve hence the normality
condition is not met. After fitting the log(sd) vs log(mean) plot, the
slope of the graph is 0.7217 hence a square root transformation for the
response should be use

\hypertarget{anova}{%
\subsection{Anova}\label{anova}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cars5 <-}\StringTok{ }\NormalTok{cars4 <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\KeywordTok{sqrt}\NormalTok{(price)}\OperatorTok{~}\StringTok{ }\NormalTok{mileage }\OperatorTok{+}\StringTok{ }\NormalTok{age }\OperatorTok{+}\NormalTok{model }\OperatorTok{+}\NormalTok{zipcode, }\DataTypeTok{data =}\NormalTok{ cars3)}
\KeywordTok{anova}\NormalTok{(cars5)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: sqrt(price)
##            Df  Sum Sq Mean Sq F value    Pr(>F)    
## mileage     1 113.300 113.300 867.276 < 2.2e-16 ***
## age         1   6.918   6.918  52.955 3.123e-12 ***
## model       2  61.057  30.528 233.685 < 2.2e-16 ***
## zipcode     1   1.087   1.087   8.318  0.004215 ** 
## Residuals 294  38.408   0.131                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

After transformed the response to square root, the anova table is made.
After taken into account mileage and age, the difference in model is
dignificant since the p value is extremely small hence model is a
significant variable. And after taken into account model, zipcode is
also significant because the p-value is less than 0.05. Therefore, model
and zipcode are important cofounding variables for price of used cars.

\hypertarget{fruit-fly-data}{%
\section{Fruit Fly Data}\label{fruit-fly-data}}

The dataset FruitFlies contains the result of an experiment concerning
the lifespan of male fruit flies.

Researchers were interested in male fruit flies and set up the following
experiment: they randomly assigned virgin male fruit flies to one of two
treatments: live alone or live in an environment where they can sense
another male fly. Then the flies were randomly allocated to either have
mating opportunities with female fruit flies or not. Two response
variables were measured: Longevity (hours after the 11th day of life)
and Activity (number of times the fly triggered a movement sensor in the
12th day of life). A potential covariate, the size of the fly's Thorax
was also measured.

Analyze the response variable Longevity. Consider both of the treatment
variables as part of your analysis.

\hypertarget{eda-1}{%
\subsection{EDA}\label{eda-1}}

\hypertarget{read-in-the-data-and-report-the-mean-and-standard-deviation-1}{%
\subsubsection{Read in the data and report the mean and standard
deviation}\label{read-in-the-data-and-report-the-mean-and-standard-deviation-1}}

Professor, I couldnt find the variable lifespan so I change it to
longevity

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{data}\NormalTok{(FruitFlies)}
\NormalTok{FruitFlies}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     ID Partners Type Longevity Thorax Sleep  Treatment
## 1    1        8    0        35   0.64    22 8 pregnant
## 2    2        8    0        37   0.68     9 8 pregnant
## 3    3        8    0        49   0.68    49 8 pregnant
## 4    4        8    0        46   0.72     1 8 pregnant
## 5    5        8    0        63   0.72    23 8 pregnant
## 6    6        8    0        39   0.76    83 8 pregnant
## 7    7        8    0        46   0.76    23 8 pregnant
## 8    8        8    0        56   0.76    15 8 pregnant
## 9    9        8    0        63   0.76     9 8 pregnant
## 10  10        8    0        65   0.76    81 8 pregnant
## 11  11        8    0        56   0.80    12 8 pregnant
## 12  12        8    0        65   0.80    15 8 pregnant
## 13  13        8    0        70   0.80    37 8 pregnant
## 14  14        8    0        63   0.84    24 8 pregnant
## 15  15        8    0        65   0.84    26 8 pregnant
## 16  16        8    0        70   0.84    17 8 pregnant
## 17  17        8    0        77   0.84    14 8 pregnant
## 18  18        8    0        81   0.84    14 8 pregnant
## 19  19        8    0        86   0.84     6 8 pregnant
## 20  20        8    0        70   0.88    25 8 pregnant
## 21  21        8    0        70   0.88    18 8 pregnant
## 22  22        8    0        77   0.92    26 8 pregnant
## 23  23        8    0        77   0.92    24 8 pregnant
## 24  24        8    0        81   0.92    29 8 pregnant
## 25  25        8    0        77   0.94    27 8 pregnant
## 26   1        0    9        40   0.64    18       none
## 27   2        0    9        37   0.70     6       none
## 28   3        0    9        44   0.72    19       none
## 29   4        0    9        47   0.72     7       none
## 30   5        0    9        47   0.72    16       none
## 31   6        0    9        47   0.76    13       none
## 32   7        0    9        68   0.78    35       none
## 33   8        0    9        47   0.80     2       none
## 34   9        0    9        54   0.84    35       none
## 35  10        0    9        61   0.84     6       none
## 36  11        0    9        71   0.84    15       none
## 37  12        0    9        75   0.84    14       none
## 38  13        0    9        89   0.84    18       none
## 39  14        0    9        58   0.88    50       none
## 40  15        0    9        59   0.88    25       none
## 41  16        0    9        62   0.88    10       none
## 42  17        0    9        79   0.88    33       none
## 43  18        0    9        96   0.88    43       none
## 44  19        0    9        58   0.92    35       none
## 45  20        0    9        62   0.92    17       none
## 46  21        0    9        70   0.92    27       none
## 47  22        0    9        72   0.92    22       none
## 48  23        0    9        75   0.92    16       none
## 49  24        0    9        96   0.92    20       none
## 50  25        0    9        75   0.94    37       none
## 51   1        1    0        46   0.64    23 1 pregnant
## 52   2        1    0        42   0.68     4 1 pregnant
## 53   3        1    0        65   0.72    20 1 pregnant
## 54   4        1    0        46   0.76    42 1 pregnant
## 55   5        1    0        58   0.76     9 1 pregnant
## 56   6        1    0        42   0.80    32 1 pregnant
## 57   7        1    0        48   0.80    66 1 pregnant
## 58   8        1    0        58   0.80    28 1 pregnant
## 59   9        1    0        50   0.82    10 1 pregnant
## 60  10        1    0        80   0.82     4 1 pregnant
## 61  11        1    0        63   0.84    12 1 pregnant
## 62  12        1    0        65   0.84    17 1 pregnant
## 63  13        1    0        70   0.84    12 1 pregnant
## 64  14        1    0        70   0.84    23 1 pregnant
## 65  15        1    0        72   0.84    40 1 pregnant
## 66  16        1    0        97   0.84    18 1 pregnant
## 67  17        1    0        46   0.88    10 1 pregnant
## 68  18        1    0        56   0.88    38 1 pregnant
## 69  19        1    0        70   0.88     7 1 pregnant
## 70  20        1    0        70   0.88    23 1 pregnant
## 71  21        1    0        72   0.88    36 1 pregnant
## 72  22        1    0        76   0.88     9 1 pregnant
## 73  23        1    0        90   0.88    21 1 pregnant
## 74  24        1    0        76   0.92    62 1 pregnant
## 75  25        1    0        92   0.92    36 1 pregnant
## 76   1        1    1        21   0.68    23   1 virgin
## 77   2        1    1        40   0.68    62   1 virgin
## 78   3        1    1        44   0.72    28   1 virgin
## 79   4        1    1        54   0.76    18   1 virgin
## 80   5        1    1        36   0.78    10   1 virgin
## 81   6        1    1        40   0.80    28   1 virgin
## 82   7        1    1        56   0.80    22   1 virgin
## 83   8        1    1        60   0.80    29   1 virgin
## 84   9        1    1        48   0.84    15   1 virgin
## 85  10        1    1        53   0.84    73   1 virgin
## 86  11        1    1        60   0.84    10   1 virgin
## 87  12        1    1        60   0.84     5   1 virgin
## 88  13        1    1        65   0.84    13   1 virgin
## 89  14        1    1        68   0.84    27   1 virgin
## 90  15        1    1        60   0.88    20   1 virgin
## 91  16        1    1        81   0.88    21   1 virgin
## 92  17        1    1        81   0.88    12   1 virgin
## 93  18        1    1        48   0.90    49   1 virgin
## 94  19        1    1        48   0.90    17   1 virgin
## 95  20        1    1        56   0.90    22   1 virgin
## 96  21        1    1        68   0.90    71   1 virgin
## 97  22        1    1        75   0.90    17   1 virgin
## 98  23        1    1        81   0.90    10   1 virgin
## 99  24        1    1        48   0.92    24   1 virgin
## 100 25        1    1        68   0.92    18   1 virgin
## 101  1        8    1        16   0.64    34   8 virgin
## 102  2        8    1        19   0.64     6   8 virgin
## 103  3        8    1        19   0.68     4   8 virgin
## 104  4        8    1        32   0.72    22   8 virgin
## 105  5        8    1        33   0.72    28   8 virgin
## 106  6        8    1        33   0.74    31   8 virgin
## 107  7        8    1        30   0.76    16   8 virgin
## 108  8        8    1        42   0.76    27   8 virgin
## 109  9        8    1        42   0.76     8   8 virgin
## 110 10        8    1        33   0.78    32   8 virgin
## 111 11        8    1        26   0.80    20   8 virgin
## 112 12        8    1        30   0.80    35   8 virgin
## 113 13        8    1        40   0.82    12   8 virgin
## 114 14        8    1        54   0.82    14   8 virgin
## 115 15        8    1        34   0.84    17   8 virgin
## 116 16        8    1        34   0.84    29   8 virgin
## 117 17        8    1        47   0.84    31   8 virgin
## 118 18        8    1        47   0.84     6   8 virgin
## 119 19        8    1        42   0.88    30   8 virgin
## 120 20        8    1        47   0.88    27   8 virgin
## 121 21        8    1        54   0.88    40   8 virgin
## 122 22        8    1        54   0.88    19   8 virgin
## 123 23        8    1        56   0.88     8   8 virgin
## 124 24        8    1        60   0.88     8   8 virgin
## 125 25        8    1        44   0.92    15   8 virgin
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{favstats}\NormalTok{(Longevity}\OperatorTok{~}\NormalTok{Treatment, }\DataTypeTok{data =}\NormalTok{ FruitFlies)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Treatment min Q1 median Q3 max  mean       sd  n missing
## 1 1 pregnant  42 50     65 72  97 64.80 15.65248 25       0
## 2   1 virgin  21 48     56 68  81 56.76 14.92838 25       0
## 3 8 pregnant  35 56     65 77  86 63.36 14.53983 25       0
## 4   8 virgin  16 32     40 47  60 38.72 12.10207 25       0
## 5       none  37 47     62 75  96 63.56 16.45215 25       0
\end{verbatim}

It seems like there is a variation in the standard deviation but it is
not big enough to be a problem.

\hypertarget{side-by-side-dotplot-1}{%
\subsubsection{Side-by-side dotplot}\label{side-by-side-dotplot-1}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{gf_point}\NormalTok{(Longevity}\OperatorTok{~}\NormalTok{Treatment, }\DataTypeTok{data =}\NormalTok{ FruitFlies)}
\end{Highlighting}
\end{Shaded}

\includegraphics{LastName_TWO-way-ANOVA_project_files/figure-latex/unnamed-chunk-8-1.pdf}
From the dotplot, it seems like the treatment group is significant in
determining the longevity of the grasshopper. But, the none and 1
pregnant treatment group do not show that much of a difference. The
treatment of 8 virgin has the lowest longevity compared to other group.

\hypertarget{fit-check-condition-1}{%
\subsection{Fit \& Check condition}\label{fit-check-condition-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{flies <-}\StringTok{ }\KeywordTok{aov}\NormalTok{(Longevity}\OperatorTok{~}\NormalTok{Treatment, }\DataTypeTok{data =}\NormalTok{ FruitFlies)}
\KeywordTok{summary}\NormalTok{(flies)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Df Sum Sq Mean Sq F value   Pr(>F)    
## Treatment     4  11939  2984.8   13.61 3.52e-09 ***
## Residuals   120  26314   219.3                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mplot}\NormalTok{(flies, }\DataTypeTok{which =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## mplot() doesn't know how to handle this kind of input.
\end{verbatim}

\begin{verbatim}
## use methods("mplot") to see a list of available methods.
\end{verbatim}

\begin{verbatim}
## mplot() doesn't know how to handle this kind of input.
\end{verbatim}

\begin{verbatim}
## use methods("mplot") to see a list of available methods.
\end{verbatim}

\begin{verbatim}
## [[1]]
\end{verbatim}

\includegraphics{LastName_TWO-way-ANOVA_project_files/figure-latex/unnamed-chunk-9-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mplot}\NormalTok{(flies, }\DataTypeTok{which =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## mplot() doesn't know how to handle this kind of input.
## use methods("mplot") to see a list of available methods.
\end{verbatim}

\begin{verbatim}
## mplot() doesn't know how to handle this kind of input.
\end{verbatim}

\begin{verbatim}
## use methods("mplot") to see a list of available methods.
\end{verbatim}

\begin{verbatim}
## [[1]]
\end{verbatim}

\includegraphics{LastName_TWO-way-ANOVA_project_files/figure-latex/unnamed-chunk-9-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{flies2 <-}\StringTok{ }\NormalTok{FruitFlies}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(Treatment)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{mean =} \KeywordTok{mean}\NormalTok{(Longevity), }\DataTypeTok{sd =} \KeywordTok{sd}\NormalTok{(Longevity))}
\NormalTok{flies2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5 x 3
##   Treatment   mean    sd
##   <fct>      <dbl> <dbl>
## 1 1 pregnant  64.8  15.7
## 2 1 virgin    56.8  14.9
## 3 8 pregnant  63.4  14.5
## 4 8 virgin    38.7  12.1
## 5 none        63.6  16.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{gf_point}\NormalTok{(}\KeywordTok{log}\NormalTok{(sd) }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(mean), }\DataTypeTok{data =}\NormalTok{ flies2) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{gf_lm}\NormalTok{(}\KeywordTok{log}\NormalTok{(sd) }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(mean), }\DataTypeTok{data =}\NormalTok{ flies2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{LastName_TWO-way-ANOVA_project_files/figure-latex/unnamed-chunk-9-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{lm}\NormalTok{(}\KeywordTok{log}\NormalTok{(sd) }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(mean), }\DataTypeTok{data =}\NormalTok{ flies2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = log(sd) ~ log(mean), data = flies2)
## 
## Coefficients:
## (Intercept)    log(mean)  
##      0.6712       0.4992
\end{verbatim}

I fit a one-way anova for this model. From the residual vs fitted plot,
it seems like there is no problem with variability. From the normal
plot, all of the points lie almost close to the line so the normality
condition is met. From the log(sd) vs log(mean) plot, it seems like the
points lie closely to the line except for 2 points but since they are
parallel to each other, it does not seem like a problem. Hence, there is
no transformation needed.

\hypertarget{anova-1}{%
\subsection{Anova}\label{anova-1}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(flies)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Df Sum Sq Mean Sq F value   Pr(>F)    
## Treatment     4  11939  2984.8   13.61 3.52e-09 ***
## Residuals   120  26314   219.3                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

From the one - way anova table, the p-value for treatment is extremely
low hence we can reject the null that the mean of all treatment effect
is the same. In conclusion, the treatment effect is a significant
variable in determining longevity of the grasshopper.

\hypertarget{oil-data}{%
\section{Oil Data}\label{oil-data}}

The data set OilDeapsorbtion is the result of a science fair experiment
run by a high school student.

The basic question concerned removing oil from sand (think an oil spill
near a beach). The student wanted to know if exposing sand with oil in
it to ultrasound could help the oil deapsorb better than sand that was
not exposed to ultrasound. There were two levels of ultrasound tested, 5
minutes and 10 minutes, and two levels of oil, 5 ml and 10 ml.
Additionally, the student wanted to know if exposure to freshwater or
saltwater made a difference, so half the samples had saltwater and the
others had distilled water. Each combination of factor levels was
replicated 5 times, with an equivalent number of control observations
(no ultrasound but all other factors equal). The response variable
reported is the difference in the amount of oil left in the experimental
run and the control run (Diff = Treatment - Control).

Analyze the response variable Diff. Consider all THREE treatment
variables as part of your analysis. Treat each variable as a factor and
fit a three-way ANOVA

\hypertarget{eda-2}{%
\subsection{EDA}\label{eda-2}}

\hypertarget{read-in-the-data-and-report-the-mean-and-standard-deviation-2}{%
\subsubsection{Read in the data and report the mean and standard
deviation}\label{read-in-the-data-and-report-the-mean-and-standard-deviation-2}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{data}\NormalTok{(}\StringTok{"OilDeapsorbtion"}\NormalTok{)}
\NormalTok{OilDeapsorbtion <-}\StringTok{ }\NormalTok{OilDeapsorbtion}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{Salt =} \KeywordTok{as.character}\NormalTok{(Salt), }\DataTypeTok{Ultra =} \KeywordTok{as.character}\NormalTok{(Ultra), }\DataTypeTok{Oil =} \KeywordTok{as.character}\NormalTok{(Oil))}

\KeywordTok{favstats}\NormalTok{(Diff}\OperatorTok{~}\NormalTok{Salt}\OperatorTok{+}\NormalTok{Ultra}\OperatorTok{+}\NormalTok{Oil, }\DataTypeTok{data=}\NormalTok{OilDeapsorbtion)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Salt.Ultra.Oil  min  Q1 median  Q3 max mean        sd n missing
## 1        0.10.10  0.5 1.0    1.0 1.5 1.5  1.1 0.4183300 5       0
## 2        1.10.10  0.5 1.0    1.0 1.5 1.5  1.1 0.4183300 5       0
## 3         0.5.10  2.0 2.0    2.0 2.5 3.0  2.3 0.4472136 5       0
## 4         1.5.10 -1.0 0.5    1.5 1.5 1.5  0.8 1.0954451 5       0
## 5         0.10.5 -0.5 0.0    0.5 1.0 1.5  0.5 0.7905694 5       0
## 6         1.10.5  0.5 1.0    1.0 1.5 1.5  1.1 0.4183300 5       0
## 7          0.5.5 -0.5 0.0    0.5 0.5 0.5  0.2 0.4472136 5       0
## 8          1.5.5  0.5 0.5    1.0 1.0 1.0  0.8 0.2738613 5       0
\end{verbatim}

From the table, it seems like there is a problem with the variability of
standard deviation because 1.095/0.274 is definitely greater than 2

\hypertarget{side-by-side-dotplot-2}{%
\subsubsection{side-by-side dotplot}\label{side-by-side-dotplot-2}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{gf_point}\NormalTok{(Diff}\OperatorTok{~}\NormalTok{Salt }\OperatorTok{|}\StringTok{ }\NormalTok{Oil, }\DataTypeTok{colour =} \OperatorTok{~}\NormalTok{Ultra, }\DataTypeTok{data =}\NormalTok{ OilDeapsorbtion)}
\end{Highlighting}
\end{Shaded}

\includegraphics{LastName_TWO-way-ANOVA_project_files/figure-latex/unnamed-chunk-12-1.pdf}
I converted Salt, Ultra and Oil to categorical value so that a dotplot
can be formed. From the dot plot, It seems like Oil level 5 does not
have level 5 ultrasound tested. Whith salt water present, the difference
seems similar except for the presence of ultrasound level 5 at oil level
10. But for freshwater, it seems like there is a difference in the
diiference.

\hypertarget{fit-and-check-condition}{%
\subsection{Fit and check condition}\label{fit-and-check-condition}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Oil <-}\StringTok{ }\KeywordTok{aov}\NormalTok{(Diff}\OperatorTok{~}\NormalTok{Salt}\OperatorTok{+}\NormalTok{Ultra}\OperatorTok{+}\NormalTok{Oil, }\DataTypeTok{data=}\NormalTok{OilDeapsorbtion)}

\KeywordTok{mplot}\NormalTok{(Oil, }\DataTypeTok{which =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## mplot() doesn't know how to handle this kind of input.
\end{verbatim}

\begin{verbatim}
## use methods("mplot") to see a list of available methods.
\end{verbatim}

\begin{verbatim}
## mplot() doesn't know how to handle this kind of input.
\end{verbatim}

\begin{verbatim}
## use methods("mplot") to see a list of available methods.
\end{verbatim}

\begin{verbatim}
## [[1]]
\end{verbatim}

\includegraphics{LastName_TWO-way-ANOVA_project_files/figure-latex/unnamed-chunk-13-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mplot}\NormalTok{(Oil, }\DataTypeTok{which =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## mplot() doesn't know how to handle this kind of input.
## use methods("mplot") to see a list of available methods.
\end{verbatim}

\begin{verbatim}
## mplot() doesn't know how to handle this kind of input.
\end{verbatim}

\begin{verbatim}
## use methods("mplot") to see a list of available methods.
\end{verbatim}

\begin{verbatim}
## [[1]]
\end{verbatim}

\includegraphics{LastName_TWO-way-ANOVA_project_files/figure-latex/unnamed-chunk-13-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Oil2 <-}\StringTok{ }\NormalTok{OilDeapsorbtion}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(Salt, Ultra, Oil)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{mean =} \KeywordTok{mean}\NormalTok{(Diff), }\DataTypeTok{sd =} \KeywordTok{sd}\NormalTok{(Diff))}

\KeywordTok{gf_point}\NormalTok{(}\KeywordTok{log}\NormalTok{(sd) }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(mean), }\DataTypeTok{data =}\NormalTok{ Oil2) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{gf_lm}\NormalTok{(}\KeywordTok{log}\NormalTok{(sd) }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(mean), }\DataTypeTok{data =}\NormalTok{ Oil2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{LastName_TWO-way-ANOVA_project_files/figure-latex/unnamed-chunk-13-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{lm}\NormalTok{(}\KeywordTok{log}\NormalTok{(sd) }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(mean), }\DataTypeTok{data =}\NormalTok{ Oil2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = log(sd) ~ log(mean), data = Oil2)
## 
## Coefficients:
## (Intercept)    log(mean)  
##    -0.72770     -0.09738
\end{verbatim}

From the residual plot, It seems like there is a problem with
variability since the points at the end of the plot is higher than the
rest.There is also a problem with normality because there is a tail and
the left end of the plot. Although it is only one point, it does seem
like a problem. From the log(sd) vs log(mean) plot, the points does not
lie closely to the line hence a transformation is needed.The slope of
the plot is -0.0978. 1 - (-0978) = 1.0978 so a quadratic transformation
of the response could be done.

\hypertarget{anova-2}{%
\subsection{ANOVA}\label{anova-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Oil3 <-}\StringTok{ }\KeywordTok{aov}\NormalTok{(Diff}\OperatorTok{^}\DecValTok{2}\OperatorTok{~}\NormalTok{Salt}\OperatorTok{+}\NormalTok{Ultra}\OperatorTok{+}\NormalTok{Oil, }\DataTypeTok{data=}\NormalTok{OilDeapsorbtion)}
\KeywordTok{summary}\NormalTok{(Oil3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             Df Sum Sq Mean Sq F value  Pr(>F)   
## Salt         1   4.73   4.727   1.903 0.17629   
## Ultra        1   6.20   6.202   2.496 0.12285   
## Oil          1  28.48  28.477  11.463 0.00173 **
## Residuals   36  89.43   2.484                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

After transforming the response to a power of 2, the p-value of salt is
high, Hence, we fail to reject the null which is the mean value of salts
group are all the same. This means that salt is not a significant
cofounding variable in determining the difference in the amount of oil
left in the experimental run and the control run. After taking into
account Salt, Ultra also has a large pvalue. Hence we fail to reject the
null that the mean value of Ultra group is different. Hence, Ultra is
not a significant cofounding variable to determine the difference in the
amount of oil left in the experimental run and the control run. Lastly,
after accounting for salt and ultra, the p-value for residual is small.
Hence, we can rejec the null that the mean of oil group is the same.
Hence, oil is a significant cofounding variable in determining the
difference in the amount of oil left in the experimental run and the
control run


\end{document}
